name: Default

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  rustfmt:
    name: rustfmt
    runs-on: ubuntu-latest
    steps:
      - name: checkout_repository
        uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: install_rust
        uses: hecrj/setup-rust-action@v1
        with:
          rust-version: stable
      - name: install_rustfmt
        run: rustup component add rustfmt
      - name: Check formatting
        run: |
          cargo fmt -- --check
